#!/usr/bin/env php
<?php

/*
 * This file is part of the lawyersoa/php-design-pattern.
 *
 * (c) lawyersoa <business@lawyersoa.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use PHPDesignPattern\Command\{
    CarDrive
};

$application = new Application();

try {
    $application->add(new CarDrive());
    $application->run();
} catch (Exception $e) {

}
